# Define the goal
std_msgs/Int32 fiducialOrientation
std_msgs/Int32 fiducialGoal
geometry_msgs/Pose goalPose
bool reverse
---
# Define the result
bool success
---
# Define a feedback message
std_msgs/String msg
 