# Define the goal
std_msgs/Int32 fiduacialNbr
geometry_msgs/Pose goalPose
geometry_msgs/Pose initPose
---
# Define the result
bool success
---
# Define a feedback message
geometry_msgs/Pose relativePose
 