# Define the goal
# Time to try to detect the fire (in seconds. If 0 detect until success)
std_msgs/Duration detect_time
---
# Define the result
bool fire_found
geometry_msgs/Point fire_position
float64[9] covariance
 
---
# Define a feedback message
#Current time since the begining (in seconds)
std_msgs/Duration current_time


