# Define the goal
geometry_msgs/PoseStamped global_goal 
---
# Define the result
bool arrived
std_msgs/Float32 finalDist
---
# Define a feedback message
std_msgs/Float32 distToGoal
geometry_msgs/Twist speed
