# Define the goal
geometry_msgs/Pose global_goal 
---
# Define the result
bool arrived
std_msgs/Float32 finalAngle
std_msgs/Float32 finalDist
---
# Define a feedback message
std_msgs/Float32 distance_to_goal
geometry_msgs/Vector3 speed
bool security_stop